"""
SwiftEye Alert Detectors — security pattern detection.

Detectors scan the capture data for security-relevant patterns (ARP spoofing,
suspicious user-agents, malicious JA3, port scanning, etc.) and return
AlertRecord objects. They run after the graph is built, using the same
AnalysisContext as analysis plugins.

Philosophy: SwiftEye is a viewer, not a judge. Alerts surface patterns to
investigate, never verdicts. Descriptions say "may indicate X", not "this is X".

Two alert sources (data model supports both from day one):
  - "detector"  — generated by SwiftEye's own analysis pipeline (Phase 1)
  - "external"  — provided by external systems like Suricata eve.json (future)

Future extension points:
  - get_charts() on AlertPluginBase for per-detector Research panel charts
  - Alert correlation (grouping related AlertRecords into composite findings)
  - Graph-structural detectors (lateral movement, beaconing, DNS tunneling)

Writing a new detector:
  1. Create backend/plugins/alerts/my_detector.py
  2. Subclass AlertPluginBase, implement detect(ctx) -> List[AlertRecord]
  3. Register in server.py detector registration block
"""

import logging
from dataclasses import dataclass, field
from abc import ABC, abstractmethod
from typing import List, Optional

logger = logging.getLogger("swifteye.alerts")


@dataclass
class AlertRecord:
    id: str                        # uuid4 short (8 chars)
    title: str                     # Detector type name, e.g. "ARP Spoofing"
    subtitle: str                  # One-line finding, e.g. "IP claimed by 2 MACs"
    severity: str                  # "high" | "medium" | "low" | "info"
    detector: str                  # Plugin name, e.g. "arp_spoofing"
    source: str                    # "detector" (generated by SwiftEye) | "external"
    source_name: str               # Human-readable source, e.g. "arp_spoofing" or "suricata"
    timestamp: Optional[float]     # Epoch of first triggering packet/session
    src_ip: Optional[str]          # Primary involved IP (src)
    dst_ip: Optional[str]          # Secondary involved IP (dst), may be None
    evidence: list                 # List of {"key": str, "value": str, "note": str}
    node_ids: list = field(default_factory=list)     # IPs involved -> for graph highlight
    edge_ids: list = field(default_factory=list)     # Edge IDs involved
    session_ids: list = field(default_factory=list)  # Session IDs involved

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "title": self.title,
            "subtitle": self.subtitle,
            "severity": self.severity,
            "detector": self.detector,
            "source": self.source,
            "source_name": self.source_name,
            "timestamp": self.timestamp,
            "src_ip": self.src_ip,
            "dst_ip": self.dst_ip,
            "evidence": self.evidence,
            "node_ids": self.node_ids,
            "edge_ids": self.edge_ids,
            "session_ids": self.session_ids,
        }


class AlertPluginBase(ABC):
    name: str = ""
    version: str = "1.0"

    @abstractmethod
    def detect(self, ctx) -> List[AlertRecord]:
        """
        Run detection against ctx.
        ctx has: packets, sessions, nodes, edges.
        Return a list of AlertRecord -- empty list if nothing found.
        DO NOT raise -- catch internally and return [].
        """
        pass


# -- Registry ----------------------------------------------------------------

_detectors: dict[str, AlertPluginBase] = {}


def register_detector(plugin: AlertPluginBase):
    _detectors[plugin.name] = plugin
    logger.info(f"Registered detector: {plugin.name} v{plugin.version}")


def get_detectors() -> dict:
    return _detectors


def run_all_detectors(ctx) -> list[dict]:
    """Run all registered detectors. Returns list of alert dicts."""
    results = []
    for name, plugin in _detectors.items():
        try:
            alerts = plugin.detect(ctx)
            results.extend(a.to_dict() for a in alerts)
        except Exception as e:
            logger.error(f"Detector '{name}' failed: {e}", exc_info=True)
    # Sort: high -> medium -> low -> info
    sev_order = {"high": 0, "medium": 1, "low": 2, "info": 3}
    results.sort(key=lambda a: (sev_order.get(a["severity"], 9), a.get("timestamp") or 0))
    return results
